use_frameworks!

platform :ios, '8.0'

target 'XLPagerTabStripObjcContinue_Example' do
  pod 'XLPagerTabStripObjcContinue', :path => '../'

  target 'XLPagerTabStripObjcContinue_Tests' do
    inherit! :search_paths

    
  end
end
